"""initial_schema

Revision ID: 4df782f0fdba
Revises: 
Create Date: 2026-08-23 13:01:12.503508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df782f0fdba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bis_entity_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_canonical_concepts_bis_entity_id'), 'canonical_concepts', ['bis_entity_id'], unique=True)
    op.create_table('hallmarking_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bis_entity_id', sa.String(), nullable=False),
    sa.Column('metal', sa.String(), nullable=False),
    sa.Column('article_type', sa.String(), nullable=False),
    sa.Column('huid', sa.String(), nullable=True),
    sa.Column('jeweller_registration', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hallmarking_records_bis_entity_id'), 'hallmarking_records', ['bis_entity_id'], unique=True)
    op.create_index(op.f('ix_hallmarking_records_huid'), 'hallmarking_records', ['huid'], unique=True)
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bis_entity_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recognition_status', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('validity', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratories_bis_entity_id'), 'laboratories', ['bis_entity_id'], unique=True)
    op.create_table('qcos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bis_entity_id', sa.String(), nullable=False),
    sa.Column('qco_identifier', sa.String(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('ministry', sa.String(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('exemptions', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qco_identifier')
    )
    op.create_index(op.f('ix_qcos_bis_entity_id'), 'qcos', ['bis_entity_id'], unique=True)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bis_entity_id', sa.String(), nullable=False),
    sa.Column('is_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('is_number')
    )
    op.create_index(op.f('ix_standards_bis_entity_id'), 'standards', ['bis_entity_id'], unique=True)
    op.create_table('concept_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['canonical_concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_standard_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['canonical_concepts.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qco_standard_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qco_bis_entity_id', sa.String(), nullable=False),
    sa.Column('standard_bis_entity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['qco_bis_entity_id'], ['qcos.bis_entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_bis_entity_id'], ['standards.bis_entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qco_standard_mappings')
    op.drop_table('concept_standard_mappings')
    op.drop_table('concept_aliases')
    op.drop_index(op.f('ix_standards_bis_entity_id'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_qcos_bis_entity_id'), table_name='qcos')
    op.drop_table('qcos')
    op.drop_index(op.f('ix_laboratories_bis_entity_id'), table_name='laboratories')
    op.drop_table('laboratories')
    op.drop_index(op.f('ix_hallmarking_records_huid'), table_name='hallmarking_records')
    op.drop_index(op.f('ix_hallmarking_records_bis_entity_id'), table_name='hallmarking_records')
    op.drop_table('hallmarking_records')
    op.drop_index(op.f('ix_canonical_concepts_bis_entity_id'), table_name='canonical_concepts')
    op.drop_table('canonical_concepts')
    # ### end Alembic commands ###
